Name: Linux.Sigma.EBPFBase
Description: |
  A Sigma Model to consume Velociraptor's EBPF events on linux.

  This is a real time monitoring profile which allows live monitoring
  of Linux systems using Sigma rules.

Preamble: |
  name: Linux.Sigma.EBPFBase
  description: |
    This artifact builds the basic set of log sources and field
    mappings used for Event driven Sigma rules on Linux.

    This model uses Velociraptor's EBPF engine which is based on
    tracee https://github.com/aquasecurity/tracee.

    This artifact was built on {{ .Time }}

  type: CLIENT_EVENT

  parameters:
    - name: Debug
      type: bool
      description: Enable full debug trace

    - name: RuleLevel
      type: choices
      default: Critical
      choices:
        - "Critical"
        - "Critical and High"
        - "Critical, High, and Medium"
        - "All"

    - name: RuleStatus
      type: choices
      default: Stable
      choices:
        - Stable
        - Stable and Experimental
        - Stable and Test
        - All Rules

    - name: RuleTitleFilter
      type: regex
      default: .
      description: Use this to filter only some rules to match

    - name: RuleExclusions
      type: csv
      description: |
        Some rules in the Hayabusa set are extremely noisy, so they
        are disabled by default.
      default: |
        RuleTitleRegex,Reason
        noisy,All rules marked noisy should be disabled by default.

    - name: SigmaRules
      description: If provided we use these rules instead of the built in set.

    - name: NTFS_CACHE_TIME
      type: int
      description: How often to flush the NTFS cache. (Default is 10 Min).
      default: "600"

    - name: EVTX_FREQUENCY
      type: int
      default: 60
      description: |
        How often in seconds to check for event log changes. Lower
        number means more real time detection but potentially higher
        CPU utilization.

ExportTemplate: |
  export: |
    -- Add some defaults
    LET X = scope()
    LET RuleLevel <= X.RuleLevel || "All"
    LET RuleStatus <= X.RuleStatus || "All Rules"
    LET RuleTitleFilter <= X.RuleTitleFilter || "."
    LET RuleExclusions <= X.RuleExclusions || NULL

    LET ExcludeRegex <= if(condition=RuleExclusions,
         then=join(array=RuleExclusions.RuleTitleRegex, sep="|"),
         else="XXXXXXX")

    LET RuleStatusRegex <= get(item=dict(
         `Stable`="stable",
         `Stable and Experimental`="stable|experimental",
         `Stable and Test`="stable|test",
         `All Rules`="."), member=RuleStatus)

    LET RuleLevelRegex <= get(item=dict(
         `Critical`="critical",
         `Critical and High`="critical|high",
         `Critical, High, and Medium`="critical|high|medium|default",
         `All`="."), member=RuleLevel)

    LET Hostname <= dict(H={ SELECT Hostname FROM info()}).H[0].Hostname

    {{ if .LogSources }}
    LET LogSources <= sigma_log_sources(
    {{ range .LogSources }}
      `{{ .Name }}`={
  {{ Indent .Query 5 }}
      },
    {{- end -}}
    `velociraptor/info/*`={ SELECT * FROM info() })
    {{ end }}

    LET FieldMapping <= parse_json(data=gunzip(string=base64decode(string="{{.Base64FieldMapping}}")))

    LET DefaultDetails <= parse_json(data=gunzip(string=base64decode(string="{{.Base64DefaultDetailsLookup}}")))

    LET DefaultDetailsLambda = '''{{.Base64DefaultDetailsQuery}}'''
    LET RuleFilterLambda = '''x=>x.Level =~ RuleLevelRegex AND x.Status =~ RuleStatusRegex AND x.Title =~ RuleTitleFilter AND NOT x.Title =~ ExcludeRegex'''

    LET GetProcInfo(PID) = to_dict(item={
      SELECT * FROM items(item=process_tracker_get(id=System.ProcessID).Data)
         WHERE _key =~ "Name|CommandLine|CreateTime|Exe|Cwd|Username"
      }) + dict(CreateTime=timestamp(epoch=process_tracker_get(id=System.ProcessID).Data.CreateTime))

FieldMappings:

DefaultDetails:
  Query: |
    x=>get(item=DefaultDetails,
           member=format(format="%v/%v",
              args=[x.System.Provider.Name, x.System.EventID.Value])
          ) || x.Message || x.UserData || x.EventData
  Lookup:

Sources:
  "*/linux/ebpf":
    description: |
      Reports events from the ebpf subsystem.

      NOTE: Events are enriched using the process tracker. You
      probably want to also collect the `Linux.Events.TrackProcesses`
      monitoring artifact.

    samples:
      - name: "security_file_open: A file is opened"
        json: "config/samples/Linux-EBPF-security_file_open.json"
      - name: "bpf_attach: A program is loading a new eBPF program into the kernel."
        json: "config/samples/Linux-EBPF-bpf_attach.json"
      - name: "kill: Kill another process"
        json: "config/samples/Linux-EBPF-kill.json"
      - name: "module_load: A module is loaded into the kernel"
        json: "config/samples/Linux-EBPF-module_free.json"
      - name: "mount: A filesystem is mounted"
        json: "config/samples/Linux-EBPF-mount.json"
      - name: "sched_process_exec: A process starts"
        json: "config/samples/Linux-EBPF-sched_process_exec.json"
      - name: "security_socket_connect: A process is making an outbound connection"
        json: "config/samples/Linux-EBPF-security_socket_connect.json"
      - name: "security_socket_bind: A process is binding to a socket"
        json: "config/samples/Linux-EBPF-security_socket_bind.json"
      - name: "security_inode_unlink: A file is deleted"
        json: "config/samples/Linux-EBPF-security_inode_unlink.json"
      - name: "chown: A file is changing ownership"
        json: "config/samples/Linux-EBPF-chown.json"

    query: |
      SELECT *, EventData + dict(ProcInfo=GetProcInfo(PID=System.ProcessID)) AS EventData
      FROM delay(
        query={
          SELECT timestamp(epoch=now()) AS Timestamp,
                 System.EventName AS EventType,
                 System + dict(MainHostname=Hostname) AS System, EventData
          FROM watch_ebpf(events=[
              "security_file_open",
              "bpf_attach", "fchownat", "chown", "kill",
              "module_free", "module_load",
              "mount", "sched_process_exec",
              "security_socket_accept", "security_socket_bind", "security_socket_connect",
              "unlink", "security_inode_unlink"
          ])
      }, delay=1)


QueryTemplate: |
 sources:
 - query: |
    LET Result = SELECT timestamp(epoch=System.TimeCreated.SystemTime) AS Timestamp,
          System.Computer AS Computer,
          System.Channel AS Channel,
          System.EventID.Value AS EID,
          _Rule.Level AS Level,
          _Rule.Title AS Title,
          System.EventRecordID AS RecordID,
          Details,
          dict(System=System,
               EventData=X.EventData || X.UserData,
               Message=X.Message) AS _Event,
          _Match
    FROM sigma(
      rules=split(string= SigmaRules, sep_string="\n---\n"),
      log_sources= LogSources, debug=Debug,
      default_details='''{{.Base64DefaultDetailsQuery}}''',
      rule_filter="x=>x.Level =~ RuleLevelRegex AND x.Status =~ RuleStatusRegex AND x.Title =~ RuleTitleFilter AND NOT x.Title =~ ExcludeRegex",
      field_mapping= FieldMapping)

    SELECT * FROM if(condition=Debug, then={
      SELECT * FROM Result
    }, else={
      SELECT Timestamp, Computer, Channel , EID,
             Level, Title, RecordID, Details, _Event
      FROM Result
    })

DocTemplate: |
  # Linux Base eBPF Model

  This model is designed to follow eBPF events on Linux.

  Events are provided by various eBPF functions in the `watch_ebpf()`
  plugin. These events can provide security critical information which
  can be detected using Sigma Rules.

  # Log Sources

  Following is a list of recognized log sources.

  {{ range .LogSources }}
  ## `{{ .Name }}`

  {{ .Description }}

  {{ if .Samples }}
  #### Sample Events
  {{ range .Samples }}

  ##### {{ .Name }}
  <pre class="json-renderer">
  {{ ReadFile .Json }}
  </pre>
  {{ end }}

  {{ end }}

  Sample use in a sigma rule:
  ```yaml
  log_sources:
    {{- if .LogSource.Category }}
    category: {{ .LogSource.Category }}
    {{- end }}
    {{- if .LogSource.Product }}
    product: {{ .LogSource.Product }}
    {{- end }}
    {{- if .LogSource.Service }}
    service: {{ .LogSource.Service }}
    {{- end }}
  ```

  {{ end }}
