Name: Linux.EBPF.Monitoring
ImportConfigs:
  - config/linux_ebpf_base.yaml

IncludeArtifacts:
  - output/Linux.Sigma.EBPFBase.yaml

Preamble: |
  name: Linux.EBPF.Monitoring
  description: |
    This artifact packages the standard rules in the SigmaHQ
    repository https://github.com/SigmaHQ/sigma together with
    Velociraptor's eBPF Sigma model.

    You can customize this artifact using instructions at
    [Customizing Artifacts](https://sigma.velocidex.com/docs/sigma_in_velociraptor/customize/)

    This artifact was built on {{ .Time }}

  type: CLIENT_EVENT

  parameters:
    - name: RuleLevel
      type: choices
      default: All
      choices:
        - "Critical"
        - "Critical and High"
        - "Critical, High, and Medium"
        - "All"

    - name: RuleStatus
      type: choices
      default: All Rules
      choices:
        - Stable
        - Stable and Experimental
        - Stable and Test
        - All Rules

    - name: RuleTitleFilter
      type: regex
      default: .
      description: Use this to filter only some rules to match

  imports:
    - Linux.Sigma.EBPFBase

ExportTemplate: |
  export: |
       LET SigmaRules <= gunzip(string=base64decode(string="{{.Base64CompressedRules}}"))

QueryTemplate: |
   sources:
   - query: |
       SELECT *
       FROM Artifact.Linux.Sigma.EBPFBase(
          RuleLevel=RuleLevel, RuleStatus=RuleStatus,
          RuleTitleFilter=RuleTitleFilter, RuleExclusions=RuleExclusions,
          SigmaRules=SigmaRules)

# These rules are manually translated so they are all supported
RuleDirectories:
  - rules/sigma/rules/linux/file_event/
  - rules/sigma/rules/linux/process_creation/
  - rules/sigma/rules/linux/network_connection/


DocTemplate: |
  # Linux.EBPF.Monitoring artifact

  This artifact contains rules designed to monitor a Linux host using
  EBPF.

  Base Artifact: [Linux.Sigma.EBPFBase](/docs/models/linux_ebpf_base/)

  You can download the artifact pack here
  [Linux-Sigma-EBPF.zip](/artifacts/Linux-Sigma-EBPF.zip)
  and customize using instructions at
  [Customizing Artifacts](https://sigma.velocidex.com/docs/sigma_in_velociraptor/customize/)

  {{ "{{< ruleset \"index.json\" >}}" }}
