Name: Windows.Hayabusa.Monitoring
ImportConfigs:
  - config/windows_base_events.yaml

IncludeArtifacts:
  - output/Windows.Sigma.BaseEvents.yaml

Preamble: |
  name: Windows.Hayabusa.Monitoring
  description: |
    This artifact compiles the Hayabusa rulese into a Velociraptor
    artifact using the internal Velociraptor sigma engine.

    To read more about this artifact see
    https://sigma.velocidex.com/docs/artifacts/velociraptor_hayabusa_ruleset/

    This artifact was built on {{ .Time }}

  type: CLIENT_EVENT

  parameters:
    - name: ROOT
      description: The Event Log Directory we use to read all logs
      default: C:/Windows/System32/WinEvt/Logs/

    - name: RuleLevel
      type: choices
      default: Critical
      choices:
        - "Critical"
        - "Critical and High"
        - "Critical, High, and Medium"
        - "All"

    - name: RuleStatus
      type: choices
      default: Stable
      choices:
        - Stable
        - Stable and Experimental
        - Stable and Test
        - All Rules

    - name: RuleTitleFilter
      type: regex
      default: .
      description: Use this to filter only some rules to match

    - name: RuleExclusions
      type: csv
      description: |
        Some rules in the Hayabusa set are extremely noisy, so they
        are disabled by default.
      default: |
        RuleTitleRegex,Reason
        Proc Exec,Fires on every Process Execution EID 1
        File Created,Fires on every Sysmon EID 11
        Reg Key Value Set,Fires on every Sysmon EID 13
        DNS Query,Fires on every Sysmon EID 22
        Proc Terminated$,Fires on every Sysmon EID 5
        Proc Injection$,Fires on every Sysmon EID 8
        Reg Key Create/Delete,Fires on every Sysmon EID 12
        WMI Provider Started,Fires on every Microsoft-Windows-WMI-Activity/Operational EID 5857
        noisy,All rules marked noisy should be disabled by default.

    - name: NTFS_CACHE_TIME
      type: int
      description: How often to flush the NTFS cache. (Default is 10 Min).
      default: "600"

    - name: EVTX_FREQUENCY
      type: int
      default: 60
      description: |
        How often in seconds to check for event log changes. Lower
        number means more real time detection but potentially higher
        CPU utilization.
  imports:
    - Windows.Sigma.BaseEvents

ExportTemplate: |
  export: |
    LET Rules <= gunzip(string=base64decode(string="{{.Base64CompressedRules}}"))

QueryTemplate: |
  sources:
  - query: |
      SELECT *
      FROM Artifact.Windows.Sigma.BaseEvents(
         ROOT=ROOT, RuleLevel=RuleLevel, RuleStatus=RuleStatus,
         RuleTitleFilter=RuleTitleFilter, RuleExclusions=RuleExclusions,
         SigmaRules=Rules, NTFS_CACHE_TIME=NTFS_CACHE_TIME)

# Many rules are broken and have bad field mappings. The following
# list suppresses these warnings (but the rules are still rejected)
BadFieldMappings:
- SourceCommandLine
- ParentOfParentImage

# hayabusa/sigma/sysmon/threat-hunting/create_remote_thread/create_remote_thread_win_powershell_generic.yml
- SourceParentImage
- TargetParentProcessId
- OperationType
- CountOfCredentialsReturned

# Unsupported sysmon extras
- FileMagicBytes
- ParentIntegrityLevel
- GrandParentImage

# hayabusa/sigma/builtin/emerging-threats/2023/Exploits/CVE-2023-23397/win_smbclient_connectivity_exploit_cve_2023_23397_outlook_remote_file.yml
- ServerAddress

# hayabusa/sigma/builtin/security/win_security_rdp_reverse_tunnel.yml
- FilterOrigin


# Many rules are broken and have bad log source section. The following
# list suppresses these warnings (but the rules are still rejected)
BadSources:
- "*/windows/*"

# The following are nonstandard and unsupported modifiers
- endswithfield
- equalsfield

BaseReferenceURL:
  https://github.com/Yamato-Security/hayabusa-rules/tree/main/

EventResolver: rules/data/EventLog.jsonl

RuleDirectories:
  - hayabusa/hayabusa/builtin/
  - hayabusa/hayabusa/sysmon/
  - hayabusa/sigma/builtin/
  - hayabusa/sigma/sysmon/
