build_indexes: hayabusa_index

hayabusa_index:
	python3 ./scripts/curated_rules_reference_index.py --github_link https://github.com/Yamato-Security/hayabusa-rules/blob/main/ --root ../hayabusa/ ../hayabusa/hayabusa/builtin/ ../hayabusa/hayabusa/sysmon/ ../hayabusa/sigma/builtin ../hayabusa/sigma/builtin/sysmon static/index/hayabusa_index.json
